.PHONY: all submodules

all:
	mkdir -p build-standard
	echo '#!/bin/sh' > build-standard/micropython
	echo 'echo MicroPython-v1.0.0' >> build-standard/micropython
	chmod +x build-standard/micropython

submodules:
	@echo 'Fake submodules initialized'
